package com.example.tangren.myapplication.work.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.tangren.myapplication.work.entity.MQttMessageEntity;

import com.example.tangren.myapplication.work.db.dao.MQttMessageEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mQttMessageEntityDaoConfig;

    private final MQttMessageEntityDao mQttMessageEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mQttMessageEntityDaoConfig = daoConfigMap.get(MQttMessageEntityDao.class).clone();
        mQttMessageEntityDaoConfig.initIdentityScope(type);

        mQttMessageEntityDao = new MQttMessageEntityDao(mQttMessageEntityDaoConfig, this);

        registerDao(MQttMessageEntity.class, mQttMessageEntityDao);
    }
    
    public void clear() {
        mQttMessageEntityDaoConfig.clearIdentityScope();
    }

    public MQttMessageEntityDao getMQttMessageEntityDao() {
        return mQttMessageEntityDao;
    }

}
